# Importing Liabraries

In [5]:
import numpy as np
import pandas as pd

# Load Dataset

In [2]:
dataset = pd.read_csv("DigitalAd_dataset.csv")
df = dataset.copy()

# Summarize Dataset

In [4]:
print(dataset.shape)
print(dataset.head())

(400, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1


# Segregate dataset into X(Input/Independent variable) & Y (Output/ Dependent Variable)

In [7]:
X = dataset.iloc[:, :-1].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [8]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

# Splitting Dataset into Train & Test

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25, random_state=0)

In [11]:
x_train

array([[    48,  90000],
       [    22,  27000],
       [    41,  72000],
       [    34,  43000],
       [    43, 112000],
       [    36,  99000],
       [    35,  44000],
       [    42,  79000],
       [    35,  71000],
       [    38,  50000],
       [    39,  71000],
       [    33, 149000],
       [    42,  70000],
       [    35,  27000],
       [    58,  23000],
       [    35, 147000],
       [    39, 106000],
       [    32, 120000],
       [    48, 134000],
       [    41,  72000],
       [    26,  35000],
       [    37,  80000],
       [    41,  52000],
       [    35,  50000],
       [    47,  23000],
       [    46,  59000],
       [    33,  28000],
       [    40,  75000],
       [    42, 104000],
       [    32, 117000],
       [    33,  69000],
       [    32, 150000],
       [    30,  80000],
       [    50,  44000],
       [    40, 107000],
       [    40,  57000],
       [    41,  60000],
       [    40, 142000],
       [    53, 104000],
       [    27, 137000],


In [12]:
x_test

array([[    27,  96000],
       [    48,  30000],
       [    60,  34000],
       [    48,  96000],
       [    35,  77000],
       [    32,  18000],
       [    29,  47000],
       [    57,  74000],
       [    31,  15000],
       [    40,  72000],
       [    18,  44000],
       [    29,  61000],
       [    26,  32000],
       [    47,  50000],
       [    49,  28000],
       [    33, 113000],
       [    47, 113000],
       [    40,  47000],
       [    41,  80000],
       [    35,  58000],
       [    24,  84000],
       [    37,  70000],
       [    28,  59000],
       [    40,  71000],
       [    28,  32000],
       [    42,  75000],
       [    26,  15000],
       [    31,  18000],
       [    58,  38000],
       [    35,  75000],
       [    33,  60000],
       [    35,  55000],
       [    39,  77000],
       [    53, 143000],
       [    26,  17000],
       [    22,  81000],
       [    19,  21000],
       [    33,  41000],
       [    19,  70000],
       [    32,  18000],


In [ ]:
# If random_state not given, then every time it'll take randomly 75%-80% new data for testing

In [ ]:
# test_size is mandatory & random_state is optional

# Feature Scaling

In [14]:
# preprocessing
# Standardization method

# StandardScaler method is best if not requiring output data in 0-1

from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
x_train

array([[ 0.97446763,  0.56400811],
       [-1.52088611, -1.28151705],
       [ 0.30264162,  0.03671521],
       [-0.36918439, -0.81281224],
       [ 0.49459191,  1.20847722],
       [-0.1772341 ,  0.82765456],
       [-0.27320924, -0.78351819],
       [ 0.39861676,  0.24177356],
       [-0.27320924,  0.00742116],
       [ 0.01471619, -0.60775389],
       [ 0.11069133,  0.00742116],
       [-0.46515953,  2.29235707],
       [ 0.39861676, -0.02187289],
       [-0.27320924, -1.28151705],
       [ 1.93421906, -1.39869325],
       [-0.27320924,  2.23376897],
       [ 0.11069133,  1.03271291],
       [-0.56113467,  1.44282962],
       [ 0.97446763,  1.85294632],
       [ 0.30264162,  0.03671521],
       [-1.13698554, -1.04716465],
       [-0.08125895,  0.27106761],
       [ 0.30264162, -0.54916579],
       [-0.27320924, -0.60775389],
       [ 0.87849248, -1.39869325],
       [ 0.78251734, -0.34410744],
       [-0.46515953, -1.252223  ],
       [ 0.20666648,  0.12459736],
       [ 0.39861676,

In [16]:
x_test

array([[-1.04101039,  0.73977241],
       [ 0.97446763, -1.1936349 ],
       [ 2.12616935, -1.0764587 ],
       [ 0.97446763,  0.73977241],
       [-0.27320924,  0.18318546],
       [-0.56113467, -1.5451635 ],
       [-0.8490601 , -0.69563604],
       [ 1.83824392,  0.09530331],
       [-0.65710982, -1.63304565],
       [ 0.20666648,  0.03671521],
       [-1.90478668, -0.78351819],
       [-0.8490601 , -0.28551934],
       [-1.13698554, -1.1350468 ],
       [ 0.87849248, -0.60775389],
       [ 1.07044277, -1.252223  ],
       [-0.46515953,  1.23777127],
       [ 0.87849248,  1.23777127],
       [ 0.20666648, -0.69563604],
       [ 0.30264162,  0.27106761],
       [-0.27320924, -0.37340149],
       [-1.32893582,  0.38824381],
       [-0.08125895, -0.02187289],
       [-0.94503525, -0.34410744],
       [ 0.20666648,  0.00742116],
       [-0.94503525, -1.1350468 ],
       [ 0.39861676,  0.12459736],
       [-1.13698554, -1.63304565],
       [-0.65710982, -1.5451635 ],
       [ 1.93421906,

# Training

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# model = LogisticRegression(random_state=0) # optional
model.fit(x_train, y_train)

LogisticRegression()

In [18]:
#help(LogisticRegression)

Help on class LogisticRegression in module sklearn.linear_model._logistic:

class LogisticRegression(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 's

# Prediction for all Test Data

In [23]:
# Actual output
y_test

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [24]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1])

# Evaluating Model - CONFUSION MATRIX

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", cm)

acc_score = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {acc_score*100}%")

Confusion Matrix: 
 [[61  0]
 [20 19]]
Accuracy of the model: 80.0%


# Predicting, whether new customer with Age & Salary will Buy or Not

In [31]:
age = int(input("enter new customer age: "))
salary = int(input("enter new customer salary: "))
newCust = [[age, salary]] # nested list here for combining the value
result = model.predict(sc.transform(newCust))
# print(result)
if result== 1:
    print("Customer will buy the product")
else:
    print("Customer won't buy the product")

enter new customer age: 34
enter new customer salary: 50000
Customer will buy the product
